name: Release surrealdb-sql

run-name: "Release surrealdb-sql"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  release-branch:
    name: Publish surrealdb-sql crate
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: cded77eca0d9e265bc37695b478e53976268cf57

      - name: Install a TOML parser
        run: cargo install --force --locked --version 0.8.1 taplo-cli

      - name: Prepare patch branch
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          set -x

          cd sql
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a v1.1.0-surrealdb-sql -m "Release surrealdb-sql v1.1.0"
          git push --tags
          cargo publish
